map $http_host $forwarded_port {
  default $server_port;
  ~:(?<port>\d+)$ $port;
}

server {
  listen 800;
  server_name _;
  large_client_header_buffers 4 16k;

  location = /auth {
    return 301 /auth/;
  }

  location /auth/ {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $forwarded_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://keycloak:8080/auth/;
  }

  location = /oauth2/auth {
    internal;
    proxy_pass http://oauth2-proxy:4180/oauth2/auth;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $forwarded_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Original-URI $request_uri;
  }

  location /oauth2/ {
    proxy_buffer_size 16k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 32k;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $forwarded_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://oauth2-proxy:4180;
  }

  location @oauth2_start {
    return 302 $scheme://$http_host/oauth2/start?rd=$scheme://$http_host$request_uri;
  }

  location = /api {
    return 301 /api/;
  }

  location /api/ {
    auth_request /oauth2/auth;
    error_page 401 = @oauth2_start;
    auth_request_set $auth_user $upstream_http_x_auth_request_user;
    auth_request_set $auth_email $upstream_http_x_auth_request_email;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /api;
    proxy_set_header X-Auth-Request-User $auth_user;
    proxy_set_header X-Auth-Request-Email $auth_email;
    proxy_pass http://backend:8000/;
  }

  location / {
    auth_request /oauth2/auth;
    error_page 401 = @oauth2_start;
    auth_request_set $auth_user $upstream_http_x_auth_request_user;
    auth_request_set $auth_email $upstream_http_x_auth_request_email;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Auth-Request-User $auth_user;
    proxy_set_header X-Auth-Request-Email $auth_email;
    proxy_pass http://frontend:5173/;
  }
}
